
#Vosk Usage
# Python version: 3.5-3.9
# pip version: 20.3 and newer.
#
large:
	vosk-transcriber -n vosk-model-en-us-0.22 -i ../test.wav -o test.txt
record:
	arecord -f S16_LE -r 16000 -c 1  output.wav

